import AppTable from '@app/components/app-table';
import { PageTableSelectionState, Person, TableAction } from '@app/types';
import { personsTableColumns } from '@app/utils/columns';
import { fakePersons } from '@app/utils/fake-data';
import Head from 'next/head';
import { useCallback, useEffect, useReducer, useState } from 'react';

const stateReducer = (state: PageTableSelectionState, action: TableAction) => {
  switch (action.type) {
    case 'SELECT_RADIO_ITEM':
      console.log('SELECT_RADIO_ITEM', action.payload);
      return {
        ...state,
        selectedRadioItem: action.payload,
      };
    case 'SELECT_CHECKBOX_ITEM':
      return {
        ...state,
        selectedCheckBoxItems: [...action.payload],
      };

    default:
      return state;
  }
  return state;
};

export default function Home() {
  const [state, dispatch] = useReducer(stateReducer, {
    selectedRadioItem: undefined,
    selectedCheckBoxItems: [],
  });

  const [selectedRadioItem, setSelectedRadioItem] = useState<Person[]>();
  const [selectedCheckBoxItems, setSelectedCheckBoxItems] = useState<Person[]>();

  const getRowId = useCallback((row) => row.id, []);

  useEffect(() => {
    console.log('page rendered');
  }, []);

  useEffect(() => {
    selectedRadioItem && dispatch({ type: 'SELECT_RADIO_ITEM', payload: selectedRadioItem });
    selectedCheckBoxItems && dispatch({ type: 'SELECT_CHECKBOX_ITEM', payload: selectedCheckBoxItems });
  }, [selectedRadioItem, selectedCheckBoxItems]);

  return (
    <>
      <Head>
        <title>Tanstack Wrapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ width: '100%', margin: '0' }}>
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <h4 style={{ marginBottom: '10px' }}>Next.js Tanstack Table Wrapper example in TypeScript</h4>
          </div>
          <div
            style={{
              paddingTop: '20px',
              paddingBottom: '20px',
            }}
          >
            {fakePersons.length && (
              <AppTable data={fakePersons} columns={personsTableColumns} getRowId={getRowId} pageSize={5} />
            )}
          </div>
          <div
            style={{
              paddingTop: '20px',
              paddingBottom: '20px',
            }}
          >
            {fakePersons.length && (
              <AppTable
                data={fakePersons}
                columns={personsTableColumns}
                getRowId={getRowId}
                selectionMode="single"
                onSelection={(selectedRows: Person[]) => {
                  console.log('selectedRows', selectedRows);
                  setSelectedRadioItem(selectedRows);
                }}
                // rowSelection={selectedRadioItem}
                // setRowSelection={setSelectedRadioItem}
              />
            )}
          </div>
          <div
            style={{
              paddingTop: '40px',
              paddingBottom: '40px',
            }}
          >
            {fakePersons.length && (
              <AppTable
                data={fakePersons}
                columns={personsTableColumns}
                getRowId={getRowId}
                selectionMode="multiple"
                onSelection={(selectedRows: Person[]) => {
                  console.log('selectedRows', selectedRows);
                  setSelectedCheckBoxItems(selectedRows);
                }}
                // rowSelection={selectedCheckBoxItems}
                // setRowSelection={setSelectedCheckBoxItems}
              />
            )}
          </div>
          <div
            style={{
              position: 'fixed',
              bottom: 0,
              right: 0,
              width: '25vw',
              top: 0,
              border: '1px solid rgba(0, 0, 0, 0.23)',
              overflow: 'auto',
            }}
          >
            <div style={{ padding: '20px' }}>
              <h6 style={{ marginBottom: '20px' }}>Selected Radio Item from local state</h6>
              <pre>{JSON.stringify(selectedRadioItem, null, 2)}</pre>
              <h6 style={{ marginBottom: '20px' }}>Selected Radio Item from app state</h6>
              <pre>{JSON.stringify(state.selectedRadioItem, null, 2)}</pre>
              <h6 style={{ marginBottom: '20px' }}>Selected Checkdiv Items from local state</h6>
              <pre>{JSON.stringify(selectedCheckBoxItems, null, 2)}</pre>
              <h6 style={{ marginBottom: '20px' }}>Selected Checkdiv Items from app state</h6>
              <pre>{JSON.stringify(state.selectedCheckBoxItems, null, 2)}</pre>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
